import 'package:flutter/material.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedEllipse4Widget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedVisitWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedLocationPuriOdishaIndiaWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedSearchlocationWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedUsersnearmeWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedActiiveOrganisationsWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedAAshmanFoundationWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget2/generated/GeneratedRectangle8Widget1.dart';

/* Component mainpage1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainpage1Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.500007629394531,
                top: -0.0000019073486328125,
                right: null,
                bottom: null,
                width: 25.5,
                height: 339.0,
                child: GeneratedEllipse1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 54.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 372.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse3Widget1(),
              ),
              Positioned(
                left: 11.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 33.0,
                child: GeneratedLocationPuriOdishaIndiaWidget1(),
              ),
              Positioned(
                left: 4.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 30.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 77.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 28.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 88.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 13.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 139.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 30.0,
                child: GeneratedSearchlocationWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 49.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 139.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 30.0,
                child: GeneratedUsersnearmeWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 30.0,
                child: GeneratedActiiveOrganisationsWidget1(),
              ),
              Positioned(
                left: 27.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 30.0,
                child: GeneratedAAshmanFoundationWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 17.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 66.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 33.0,
                child: GeneratedVisitWidget1(),
              ),
              Positioned(
                left: 342.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 57.0,
                child: GeneratedEllipse4Widget1(),
              ),
              Positioned(
                left: -5.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 278.0,
                child: GeneratedRectangle7Widget1(),
              )
            ]),
      ),
    ));
  }
}
