import 'package:flutter/material.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedOrWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedCreateaccountWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedCityorLocationWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedFullnameWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedContactnumberWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedsignupwidget/generated/GeneratedLine10Widget.dart';

/* Frame signup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.500007629394531,
                top: -0.0000019073486328125,
                right: null,
                bottom: null,
                width: 25.5,
                height: 339.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: -268.0,
                top: -259.0,
                right: null,
                bottom: null,
                width: 701.5,
                height: 580.8538208007812,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 511.0,
                right: null,
                bottom: null,
                width: 338.00592041015625,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 337.9999694824219,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 64.0,
                child: GeneratedSignUpWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 338.00146484375,
                height: 1.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 1.0,
                child: GeneratedLine9Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 653.0,
                right: null,
                bottom: null,
                width: 338.0014953613281,
                height: 1.0,
                child: GeneratedLine10Widget(),
              ),
              Positioned(
                left: 83.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 56.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 56.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 43.0,
                child: GeneratedFullnameWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 33.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 30.0,
                child: GeneratedContactnumberWidget(),
              ),
              Positioned(
                left: 134.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 33.0,
                child: GeneratedCreateaccountWidget(),
              ),
              Positioned(
                left: 179.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 36.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 203.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 36.0,
                child: GeneratedOrWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 624.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 30.0,
                child: GeneratedCityorLocationWidget(),
              )
            ]),
      ),
    ));
  }
}
