import 'package:flutter/material.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedAreyougoingWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedPostsWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedRajbabbarpostedaneventWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/Generated3kmsawayWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedRectangle14Widget4.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedRectangle6Widget7.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedEllipse5Widget3.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedEllipse1Widget7.dart';
import 'package:flutterapp/clean_20beachapp/generatedlatestpostswidget/generated/GeneratedGopalpurCleanBeachCampaignWidget.dart';

/* Frame latestposts
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLatestpostsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.500007629394531,
                top: -0.0000019073486328125,
                right: null,
                bottom: null,
                width: 25.5,
                height: 339.0,
                child: GeneratedEllipse1Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 54.0,
                child: GeneratedRectangle6Widget7(),
              ),
              Positioned(
                left: 179.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 30.0,
                child: GeneratedPostsWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 30.0,
                child: GeneratedRectangle14Widget4(),
              ),
              Positioned(
                left: 366.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse5Widget3(),
              ),
              Positioned(
                left: 35.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 143.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 30.0,
                child: GeneratedRajbabbarpostedaneventWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 30.0,
                child: GeneratedGopalpurCleanBeachCampaignWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 30.0,
                child: Generated3kmsawayWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 42.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 30.0,
                child: GeneratedAreyougoingWidget(),
              ),
              Positioned(
                left: 321.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 23.0,
                child: GeneratedRectangle18Widget(),
              )
            ]),
      ),
    ));
  }
}
