import 'package:flutter/material.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedEllipse3Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedActiiveOrganisationsWidget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedUsersnearmeWidget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedAAshmanFoundationWidget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedVisitWidget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedEllipse4Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedLocationPuriOdishaIndiaWidget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedSearchlocationWidget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedEllipse1Widget3.dart';
import 'package:flutterapp/clean_20beachapp/generatedmainpage1widget3/generated/GeneratedRectangle14Widget.dart';

/* Frame mainpage1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainpage1Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.500007629394531,
                top: -0.0000019073486328125,
                right: null,
                bottom: null,
                width: 25.5,
                height: 339.0,
                child: GeneratedEllipse1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: -3.0,
                right: null,
                bottom: null,
                width: 415.0,
                height: 54.0,
                child: GeneratedRectangle6Widget3(),
              ),
              Positioned(
                left: 372.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse3Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 317.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 33.0,
                child: GeneratedLocationPuriOdishaIndiaWidget2(),
              ),
              Positioned(
                left: 10.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 30.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: 181.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 28.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 267.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 26.0,
                child: GeneratedSearchlocationWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 68.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 30.0,
                child: GeneratedActiiveOrganisationsWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 30.0,
                child: GeneratedAAshmanFoundationWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 17.0,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 67.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 33.0,
                child: GeneratedVisitWidget2(),
              ),
              Positioned(
                left: 342.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 57.0,
                child: GeneratedEllipse4Widget2(),
              ),
              Positioned(
                left: -1.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 775.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 49.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 132.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 30.0,
                child: GeneratedUsersnearmeWidget2(),
              )
            ]),
      ),
    ));
  }
}
