import 'package:flutter/material.dart';
import 'package:flutterapp/clean_20beachapp/generatedchatpagewidget/generated/GeneratedRectangle6Widget4.dart';
import 'package:flutterapp/clean_20beachapp/generatedchatpagewidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedchatpagewidget/generated/GeneratedEllipse1Widget4.dart';
import 'package:flutterapp/clean_20beachapp/generatedchatpagewidget/generated/GeneratedChatBoxWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedchatpagewidget/generated/GeneratedRectangle14Widget1.dart';

/* Frame chatpage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.500007629394531,
                top: -0.0000019073486328125,
                right: null,
                bottom: null,
                width: 25.5,
                height: 339.0,
                child: GeneratedEllipse1Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 54.0,
                child: GeneratedRectangle6Widget4(),
              ),
              Positioned(
                left: 163.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 30.0,
                child: GeneratedChatBoxWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 30.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 366.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse5Widget(),
              )
            ]),
      ),
    ));
  }
}
