import 'package:flutter/material.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedRectangle14Widget5.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedUsernameWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedEllipse5Widget4.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedMyAccountWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedEllipse1Widget8.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedRectangle6Widget8.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedPuribhubaneswarIndiaWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedaccountwidget/generated/GeneratedTextWidget.dart';

/* Frame ACCOUNT
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedACCOUNTWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.500007629394531,
                top: -0.0000019073486328125,
                right: null,
                bottom: null,
                width: 25.5,
                height: 339.0,
                child: GeneratedEllipse1Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 54.0,
                child: GeneratedRectangle6Widget8(),
              ),
              Positioned(
                left: 153.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 30.0,
                child: GeneratedMyAccountWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 30.0,
                child: GeneratedRectangle14Widget5(),
              ),
              Positioned(
                left: 366.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse5Widget4(),
              ),
              Positioned(
                left: 159.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 166.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedUsernameWidget1(),
              ),
              Positioned(
                left: 109.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 24.0,
                child: GeneratedTextWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 33.0,
                child: GeneratedPuribhubaneswarIndiaWidget(),
              )
            ]),
      ),
    ));
  }
}
