import 'package:flutter/material.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedRectangle6Widget5.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedCantfindwhatyouarelookingforAddamissingplacehereWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedEllipse1Widget5.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedReportPlacesWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedMyconnectionsWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedreportplaceswidget/generated/GeneratedEllipse5Widget1.dart';

/* Frame reportplaces
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReportplacesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.500007629394531,
                top: -0.0000019073486328125,
                right: null,
                bottom: null,
                width: 25.5,
                height: 339.0,
                child: GeneratedEllipse1Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 54.0,
                child: GeneratedRectangle6Widget5(),
              ),
              Positioned(
                left: 135.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 30.0,
                child: GeneratedReportPlacesWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 30.0,
                child: GeneratedRectangle14Widget2(),
              ),
              Positioned(
                left: 366.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse5Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 89.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 58.0,
                child:
                    GeneratedCantfindwhatyouarelookingforAddamissingplacehereWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 356.01263427734375,
                height: 1.0,
                child: GeneratedLine15Widget(),
              ),
              Positioned(
                left: -451.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 823.0,
                child: GeneratedMyconnectionsWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 356.005615234375,
                height: 1.0,
                child: GeneratedLine16Widget(),
              )
            ]),
      ),
    ));
  }
}
