import 'package:flutter/material.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedUsernameWidget2.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedBeach1Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedNewuserSignuphereWidget.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/clean_20beachapp/generatedloginpagewidget/generated/GeneratedWeVolunteerWidget.dart';

/* Frame login page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(229, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 535.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 332.0135498046875,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 951.0,
                child: GeneratedBeach1Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 115.0,
                child: GeneratedWeVolunteerWidget(),
              ),
              Positioned(
                left: 86.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 56.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 171.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 31.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 33.0,
                child: GeneratedNewuserSignuphereWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 329.96417236328125,
                right: null,
                bottom: null,
                width: 329.0060729980469,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 434.96417236328125,
                right: null,
                bottom: null,
                width: 329.0060729980469,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 36.0,
                child: GeneratedUsernameWidget2(),
              ),
              Positioned(
                left: 42.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 36.0,
                child: GeneratedPasswordWidget1(),
              )
            ]),
      ),
    ));
  }
}
